### ISSUE TITLE
提议API修改

### ISSUE THREAD

**Issue by realquantumcookie** [InteractivePlus/InteractiveSSO-Captcha#1]
为了兼容最新版InteractiveSSO主系统，需要在原验证码API上做出修改

1. 验证码答案锁定为5位HexString
2. 所有原API上的错误代码作废, Captcha系统可自主设计API和错误代码, 只需给主系统提供查询验证状态的API和给前端提供直接的API即可。
3. 申请验证码(1.1)部分的API添加一个HTTP请求时的scope参数，这个参数将在下面定义的新API中返回给SSO主系统，用以主系统验证验证码用途(scope需要存入数据库)
4. 在提交完验证码后, 验证码后端需要**保留验证码信息**(可以丢弃口令等信息, 只要留id和已验证成功的状态, 以及scope参数就可以了
5. 考虑使用Redis *(可选)*
6. **添加验证Captcha提交状态的API供主系统做验证**，如下:

### 1.3 主系统查询验证码状态

此API用来让SSO主系统查询验证码被验证状态。

---

#### 1.3.1 请求方式

|HTTP Method|URL|成功HTTP Code|
|-|-|-|
|GET|/captcha/{{captcha_id}}/submitStatus|200 OK|

#### 1.3.2 参数

|参数|类型|可选|注释|
|-|-|-|-|
|captcha_id|string|-|填入URL|
|secret_phrase|string|-|主系统和验证码系统沟通密钥|

#### 1.2.3 返回值

失败时(密钥错误)会返回 `CREDENTIAL_NOT_MATCH`错误代码, 
失败时(captcha_id不存在)会返回`ITEM_DOES_NOT_EXIST`错误代码.

成功时`dataKey-data`定义: 

|参数|类型|可选|注释|
|-|-|-|-|
|scope|string|-|申请验证码时的scope参数|

成功时`rootKey-data`定义: 无特殊键值

**Comment by MeteorsLiu** [comment]
Waiting for testing
