### ISSUE TITLE
添加Captcha被提交状态

### ISSUE THREAD

**Issue by realquantumcookie** [InteractivePlus/InteractiveSSO-Captcha#2]
Redis里面的Captcha应该再储存一个提交状态的数据，并在SubmitCaptcha时进行修改 => 在CheckSubmitStatus的时候进行检查。
新API Doc随后给出。

**Comment by realquantumcookie** [comment]
https://www.interactiveplus.org/TechDoc/InteractiveSSO/SimpleCaptcha/SimpleCaptcha.html
以上为新Captcha API Doc 关注一下CheckSubmitStatus那个API

**Comment by MeteorsLiu** [comment]
新接口已完成添加，等待代码审查

**Comment by realquantumcookie** [comment]
其实应该是无新接口的，就是单纯改下老接口...
https://www.interactiveplus.org/TechDoc/InteractiveSSO/SimpleCaptcha/SimpleCaptcha.html#get-/captcha/-captchaId-/submitStatus
另: 看QQ里的备注

**Comment by MeteorsLiu** [comment]
已完成再次修改

**Comment by realquantumcookie** [comment]
Code Review commit 1fe4586dd9ac671144fca2c8f57aa105f969bf1a
